import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { approve, flight, pendingReports, report, saveFlight, saveReport } from "../flight-data.js";
import { adminChatId, inlineButton, inlineKeyboard, isOwner, registerMainMenuItem, requireOwner } from "../toolkit/index.js";

const composer = new Composer<Ctx>();
registerMainMenuItem({ label: "Manage reports", data: "admin:desk", order: 90 });
const notifyPilot = async (ctx: Ctx, pilot: number, text: string) => { try { await ctx.api.sendMessage(pilot, text); } catch { /* pilots may block the bot; owner work continues */ } };
async function desk(ctx: Ctx) { const items = await pendingReports(); if (!items.length) { await ctx.reply("No reports need manual review."); return; } const rows = items.slice(0, 8).map((r) => [inlineButton(`Review report`, `admin:report:${r.report_id}`)]); await ctx.reply("Reports needing review", { reply_markup: inlineKeyboard(rows) }); }
const ownerCtx = (ctx: unknown) => ctx as Parameters<typeof requireOwner>[0];
composer.callbackQuery("admin:desk", async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ownerCtx(ctx)))) return; await desk(ctx); });
composer.callbackQuery(/^admin:report:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ownerCtx(ctx)))) return; const r = await report(ctx.match[1]); if (!r) { await ctx.reply("That report is no longer available."); return; } const linked = r.linked_flight_id ? await flight(r.linked_flight_id) : undefined; const text = `Report review\nStatus: ${r.status}\n${linked ? `Flight: ${linked.flight_number}` : "No flight is linked"}`; const buttons = linked ? [[inlineButton("Approve", `admin:approve:${r.report_id}`), inlineButton("Reject", `admin:reject:${r.report_id}`)]] : [[inlineButton("Reject", `admin:reject:${r.report_id}`)]]; await ctx.reply(text, { reply_markup: inlineKeyboard(buttons) }); });
composer.callbackQuery(/^admin:approve:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ownerCtx(ctx)))) return; const r = await report(ctx.match[1]); if (!r) { await ctx.reply("That report is no longer available."); return; } const done = await approve(r, "admin_adjustment"); if (!done) { await ctx.reply("This report needs a linked flight and valid times before approval."); return; } await notifyPilot(ctx, r.pilot_telegram_id, `Your report for ${done.flight.flight_number} was approved. €${done.amount.toFixed(2)} was credited.`); const owner = adminChatId(ctx as unknown as { env?: Record<string, unknown> }); if (owner) await notifyPilot(ctx, Number(owner), `Manual approval posted for ${done.flight.flight_number}.`); await ctx.reply(`Approved ${done.flight.flight_number}. €${done.amount.toFixed(2)} was credited.`); });
composer.callbackQuery(/^admin:reject:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); if (!(await requireOwner(ownerCtx(ctx)))) return; const r = await report(ctx.match[1]); if (!r) { await ctx.reply("That report is no longer available."); return; } r.status = "Rejected"; await saveReport(r); if (r.linked_flight_id) { const f = await flight(r.linked_flight_id); if (f && f.status !== "Approved") { f.status = "RequiresReview"; await saveFlight(f); } } await notifyPilot(ctx, r.pilot_telegram_id, "Your report was not approved. Contact the administrator if you need it reviewed again."); await ctx.reply("The report was rejected and the pilot was notified."); });
// Owner-only typed shortcut is intentionally not published as a command.
composer.hears("admin desk", async (ctx) => { if (!isOwner(ctx)) return; await desk(ctx); });
export default composer;
